import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${inter.variable} h-full antialiased font-sans`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        {/* Botón flotante de WhatsApp */}
        <a 
          href="https://wa.me/584125040440" 
          target="_blank" 
          rel="noopener noreferrer"
          className="fixed bottom-6 right-6 bg-[#25D366] text-white p-4 rounded-full shadow-lg hover:shadow-xl transition-all transform hover:scale-110 z-50 flex items-center justify-center"
          aria-label="Contactar por WhatsApp"
        >
          <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.588-5.946 0-6.556 5.332-11.888 11.888-11.888 3.176 0 6.163 1.236 8.41 3.483 2.246 2.246 3.482 5.234 3.482 8.41 0 6.556-5.332 11.888-11.888 11.888-2.008 0-3.978-.512-5.728-1.484l-6.265 1.7zm6.34-3.15c1.558.924 3.41 1.411 5.3 1.411 5.617 0 10.188-4.57 10.188-10.188 0-2.72-1.057-5.275-2.977-7.194-1.92-1.919-4.475-2.977-7.193-2.977-5.618 0-10.188 4.57-10.188 10.188 0 1.886.516 3.722 1.492 5.311L1.242 22.75l6.335-1.66zM17.472 14.397c-.3-.149-1.777-.876-2.047-.975-.27-.099-.466-.149-.663.149-.197.298-.761.975-.933 1.173-.173.199-.346.223-.646.074-.3-.149-1.265-.466-2.41-1.484-.89-.794-1.49-1.774-1.665-2.073-.173-.299-.018-.46.131-.609.135-.133.3-.346.45-.52.15-.173.2-.298.3-.497.1-.198.05-.371-.025-.52-.075-.149-.663-1.597-.91-2.194-.24-.58-.485-.5-.663-.51-.172-.007-.37-.007-.568-.007-.198 0-.52.074-.793.371-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.777-.726 2.027-1.427.25-.702.25-1.303.175-1.427-.075-.124-.27-.199-.57-.348z" />
          </svg>
        </a>
      </body>
    </html>
  );
}
